name: Ubuntu SSH

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-ubuntu-${{ github.run_id }}

      - name: Create user
        run: |
          sudo useradd -m rdpuser
          echo "rdpuser:Amirali.138800" | sudo chpasswd
          sudo usermod -aG sudo rdpuser

      - name: Show connection info
        run: |
          echo "User: rdpuser"
          echo "Password: Amirali.138800"
          tailscale ip -4

      - name: Keep Alive
        run: |
          while true; do sleep 600; done
